version: '3'

services:
  backend:
    image: backend-image
    build:
      context: ./Markdown-Blog-master
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/your_database_name
    depends_on:
      - mongo

  frontend:
    image: frontend-image
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"